#!/bin/bash
#
# Script to run make using the Makefile for this OS
#
if (test $# -eq 0) then
        echo There should at least be one argument......
else

if [ `uname` = Darwin ]; then
        make -f ./Makefile.Darwin $1
elif [ `uname` = Linux ]; then
        if [ `uname -r` = "3.16.0-30-generic" ]; then
                make -f ./Makefile.tim $1
        elif [ `uname -r` = "2.6.32-642.1.1.el6.x86_64" ]; then
		make -f ./Makefile.Raijin $1
	else
                make -f ./Makefile.Linux $1
        fi
else
        make -f ./Makefile.other $1
fi

fi
