PYINCLUDE = /usr/local/python-2.7.1/include/python2.7

all: overlap


overlap: overlap.i
	swig -python overlap.i
	gcc -c overlap.c overlap_wrap.c -I$(PYINCLUDE) -lgsl -lgslcblas -lm
	ld -shared overlap.o overlap_wrap.o -o _overlap.so -lgsl -lgslcblas -lm


clean:
	rm -f overlap.o
	rm -f overlap_wrap.*
	rm -f _overlap.so
	rm -f overlap.pyc
	rm -f overlap.py
