##### Select resources #####
#PBS -N emcee-demo
#PBS -l select=1:ncpus=4:mpiprocs=4
##### Queue #####
#PBS -q largemem
##### Mail Options #####
# Send an email at job start, end and if aborted
#PBS -m abe
##### Change to your working directory #####
cd /home/tcrun/chronostar/avatar_scripts
##### Execute Program #####
#####/pkg/linux/anaconda/bin/mpirun -np 4 python emcee_demo.py
/pkg/linux/anaconda/bin/mpirun -np 4 /pkg/linux/anaconda/bin/python emcee_demo.py
