##### Select resources #####
#PBS -N synthSuite200
#PBS -l select=1:ncpus=28:mpiprocs=28
#### Request exclusive use of core ####
#PBS  -l place=scatter:excl
##### Queue #####
#PBS -q smallmem
##### Mail Options #####
# Send an email at job start, end and if aborted
#PBS -m abe
##### Change to your working directory #####
cd /home/tcrun/chronostar/scripts
##### Execute Program #####
/pkg/linux/anaconda/bin/python perform_many_synth_fits.py 7
