from __future__ import print_function, division

"""
Checking all the new BPMG members from Gaia DR2 stars to see if they're
featured as members elsewhere, also just to get their main designations.
"""

from astropy.table import Table
import numpy as np
import sys
sys.path.insert(0, '..')
import chronostar.synthesiser as syn
import chronostar.datatool as dt
import chronostar.coordinate as coord

import banyan_parser as bp

rdir = '../results/em_fit/beta_Pictoris_wgs_inv2_5B_res/'
final_memb_file = rdir + 'final_membership.npy'
bp_star_pars_file = '../data/beta_Pictoris_with_gaia_small_xyzuvw.fits'
gagne_star_pars_file = '../data/gagne_bonafide_full_kinematics_with_lit_and' \
                       '_best_radial_velocity_comb_binars.fits'

z = np.load(final_memb_file)
bp_sp = dt.loadDictFromTable(bp_star_pars_file)
gg_sp = dt.loadDictFromTable(gagne_star_pars_file)

banyan_data = bp.readBanyanTxtFile()

bd_ras = []
bd_des = []
for row in banyan_data:
    if row[3] == '':
        bd_ras.append(None)
        bd_des.append(None)
    else:
        bd_ras.append(coord.convertRAtoDeg(row[3], row[4], row[5]))
        bd_des.append(coord.convertDEtoDeg(row[6], row[7], row[8]))

bd_ras_arr = np.array(bd_ras, dtype=np.float64)
bd_des_arr = np.array(bd_des, dtype=np.float64)

gg_sp['table']['gagne_ra'] = bd_ras_arr
gg_sp['table']['gagne_ra'].unit = 'deg'
gg_sp['table']['gagne_de'] = bd_des_arr
gg_sp['table']['gagne_de'].unit = 'deg'

# failed_banyan_mask = np.where(np.isnan(bp_sp['table']['U']))
failed_banyan_mask = np.where(np.isnan(gg_sp['table']['ra']))

Table.write(
    gg_sp['table'],
    '../data/gagne_bonafide_full_kinematics_with_lit_and_best_radial_'
    'velocity_comb_binars_with_banyan_radec.fits',
    overwrite=True,
)

comp_a = bp_sp['table'][np.array(bp_sp['indices'])\
    [np.where(np.argmax(z, axis=1) == 0)]]

comp_d = bp_sp['table'][np.array(bp_sp['indices'])\
    [np.where(np.argmax(z, axis=1) == 3)]]

new_bpmg = comp_a[np.where(comp_a['Moving group'] != 'beta Pictoris')]

new_banyan_membs = np.array([
    3292922293081928192,
    3181961503752885248,
    3290081910949989888,  # slightly brighter
    3290081906654767616,  # companion of ^^
    3209947441933983744,
    2477815222028038272,
    4093006560668685568,  # proper motion needed to confirm
    3393207610483520896,
    5924485966955008896,  # THIS STAR WE ALSO DISCOVERED
    6631762764424312960, # HD 173167, BPMG member
], dtype=np.str)

main_designations = np.array([
    'HD 287167',
    'HD 32965',
    'TYC 698-538-1',
    'TYC 698-538-2',
    'BD-05 1229',
    'EX Cet',
    'HD 313300',
    'V1841 Ori',
    'CD-54 7336',
    'HD 173167',
])

already_discov_by_banyan_mask = np.where(np.isin(new_bpmg['source_id'],
                                                 new_banyan_membs))


# BPMG member stars from SIMBAD
#   this list was generated by first querying simbad with the Gaia DR2 ids
#   for all the 'new' (i.e. stars that aren't BANYAN members with full 6D
#   kinematics) and seeing if the stars had 'BPMG' listed as a parent.
new_bpmg_in_simbad = {
    6700649538727351040 : 'V* V5663 Sgr',
    6833292181958100224 : 'GSC 06354-00357',
    6747106443324127488 : '2MASS J20013718-3313139',
    6631685008336771072 : 'Smethells 20',
    6631762764424312960 : 'HD 173167',
}

# 2MASS identifiers for all the 'new' (as defined above) members for BPMG
#    this list was generated by querying simbad with the Gaia DR2 ids and
#    requesting the 2MASS identifier

# NOTE: maybe come back and redo this with 'all' chronostar BPMG members
new_bpmg = {
    6833291426043854976: '2MASS J21100461-1920302', # in Shkolnik
    4107812485571331328: '2MASS J17150362-2749397', # in Shkolnik
    4067828843907821824: '2MASS J17520173-2357571',
    6854064945906527104: '2MASS J20174317-2106346',
    6700649538727351040: '2MASS J20055640-3216591', # V* V5663 Sgr, BPMG member, also in Shkolnik
    6833292181958100224: '2MASS J21100535-1919573', # GSC 06354-00357, BPMG member, also in Shkolnik
    4057573802035360896: '2MASS J17453733-2824269',
    6747106443324127488: '2MASS J20013718-3313139', # 2MASS J20013718-3313139', BPMG member, also in Shkolnik
    5963633872326630272: '2MASS J17024014-4521587',
    6731752867256886144: '2MASS J19012866-3422354',
    4038504701367019648: '2MASS J18183181-3503026',
    6723183789033085824: '2MASS J18283208-4129081',
    6631685008336771072: '2MASS J18465255-6210366', # Smethells 20, BPMG member, also in Shkolnik
    6705107126367751168: '2MASS J18265401-4807022',
    6650036304082834560: '2MASS J18443965-5506502',
    6631762764424312960: '2MASS J18480637-6213470', # HD 173167, BPMG member, also in Shkolnik, and discovered by BANYAN XII
    6470519830886970880: '2MASS J20524162-5316243',
    6633474669669267712: '2MASS J19010683-5853301',
    6512664180298450688: '2MASS J22552718-5218094', # photometric outlier
    5833110434673386240: '2MASS J15553295-6010404',
    6400161703868444800: '2MASS J21212446-6654573', # in Shkolnik
    5655284731152528768: '2MASS J09055753-2131573',
    6854064945906527488: '',                        # photometric outlier
    4050178830427649024: '',
    6882838031331951488: '',
    6754492966739292928: '',
    4035322057507690752: '',
}

shkol_bpmg_membs = np.array([
    '2MASS J00065008-2306271',
    '2MASS J00172353-6645124',
    '2MASS J00233468+2014282',
    '2MASS J00274534-0806046',
    '2MASS J00275023-3233060',
    '2MASS J00275035-3233238',
    '2MASS J00325584-4405058',
    '2MASS J00440332+0228112',
    '2MASS J00464841+0715177',
    '2MASS J01071194-1935359',
    '2MASS J01112542+1526214',
    '2MASS J01132817-3821024',
    '2MASS J01294256-0823580',
    '2MASS J01351393-0712517',
    '2MASS J01354915-0753470',
    '2MASS J01365516-0647379',
    '2MASS J01373545-0645375',
    '2MASS J01373940+1835332',
    '2MASS J01535076-1459503',
    '2MASS J02172472+2844305',
    '2MASS J02172527+2844423',
    '2MASS J02175601+1225266',
    '2MASS J02232663+2244069',
    '2MASS J02261625+0617331',
    '2MASS J02272804+3058405',
    '2MASS J02272924+3058246',
    '2MASS J02282694+0218331',
    '2MASS J02303239-4342232',
    '2MASS J02304623-4343493',
    '2MASS J02365171-5203036',
    '2MASS J02412589+0559181',
    '2MASS J02501167-0151295',
    '2MASS J02534448-7959133',
    '2MASS J03111547+0106307',
    '2MASS J03323578+2843554',
    '2MASS J03350208+2342356',
    '2MASS J04373613-0228248',
    '2MASS J04373746-0229282',
    '2MASS J04433761+0002051',
    '2MASS J04435686+3723033',
    '2MASS J04480085+1439583',
    '2MASS J04480258+1439516',
    '2MASS J04593483+0147007',
    '2MASS J05004714-5715255',
    '2MASS J05015881+0958587',
    '2MASS J05082729-2101444',
    '2MASS J05120636-2949540',
    '2MASS J05195327+0617258',
    '2MASS J05200029+0613036',
    '2MASS J05203182+0616115',
    '2MASS J05241914-1601153',
    '2MASS J05270477-1154033',
    '2MASS J05294468-3239141',
    '2MASS J05335981-0221325',
    '2MASS J05471708-5103594',
    '2MASS J06131330-2742054',
    '2MASS J06182824-7202416',
    '2MASS J08173943-8243298',
    '2MASS J08224744-5726530',
    '2MASS J09360429+3733104',
    '2MASS J09361593+3731456',
    '2MASS J10141918+2104297',
    '2MASS J10172689-5354265',
    '2MASS J10593834+2526155',
    '2MASS J10593870+2526138',
    '2MASS J11493184-7851011',
    '2MASS J13545390-7121476',
    '2MASS J14141700-1521125',
    '2MASS J14142141-1521215',
    '2MASS J14252913-4113323',
    '2MASS J15385679-5742190',
    '2MASS J15385757-5742273',
    '2MASS J16181789-2836502',
    '2MASS J16430128-1754274',
    '2MASS J16572029-5343316',
    '2MASS J17150219-3333398',
    '2MASS J17150362-2749397',
    '2MASS J17172550-6657039',
    '2MASS J17173128-6657055',
    '2MASS J17292067-5014529',
    '2MASS J17295506-5415487',
    '2MASS J17414903-5043279',
    '2MASS J17483374-5306433',
    '2MASS J18030341-5138564',
    '2MASS J18030409-5138561',
    '2MASS J18064990-4325297',
    '2MASS J18141047-3247344',
    '2MASS J18142207-3246100',
    '2MASS J18151564-4927472',
    '2MASS J18195221-2916327',
    '2MASS J18202275-1011131',
    '2MASS J18420483-5554126',
    '2MASS J18420694-5554254',
    '2MASS J18452691-6452165',
    '2MASS J18453704-6451460',
    '2MASS J18465255-6210366',
    '2MASS J18480637-6213470',
    '2MASS J18504448-3147472',
    '2MASS J18530587-5010499',
    '2MASS J18580415-2953045',
    '2MASS J18580464-2953320',
    '2MASS J19102820-2319486',
    '2MASS J19114467-2604085',
    '2MASS J19225122-5425263',
    '2MASS J19225894-5432170',
    '2MASS J19233820-4606316',
    '2MASS J19243494-3442392',
    '2MASS J19312434-2134226',
    '2MASS J19355595-2846343',
    '2MASS J19560294-3207186',
    '2MASS J19560438-3207376',
    '2MASS J20004841-7523070',
    '2MASS J20013718-3313139',
    '2MASS J20041810-2619461',
    '2MASS J20055640-3216591',
    '2MASS J20090521-2613265',
    '2MASS J20100002-2801410',
    '2MASS J20135152-2806020',
    '2MASS J20333759-2556521',
    '2MASS J20334670-3733443',
    '2MASS J20415111-3226073',
    '2MASS J20434114-2433534',
    '2MASS J20450949-3120266',
    '2MASS J20554767-1706509',
    '2MASS J20560274-1710538',
    '2MASS J21100461-1920302',
    '2MASS J21100535-1919573',
    '2MASS J21103096-2710513',
    '2MASS J21103147-2710578',
    '2MASS J21140802-2251358',
    '2MASS J21212446-6654573',
    '2MASS J21212873-6655063',
    '2MASS J21374019+0137137',
    '2MASS J22004158+2715135',
    '2MASS J22081363+2921215',
    '2MASS J22424896-7142211',
    '2MASS J22445794-3315015',
    '2MASS J22450004-3315258',
    '2MASS J23172807+1936469',
    '2MASS J23301341-2023271',
    '2MASS J23314492-0244395',
    '2MASS J23323085-1215513',
    '2MASS J23353085-1908389',
    '2MASS J23500639+2659519',
    '2MASS J23512227+2344207',
    '2MASS J23542220-0811289',
    # all below were 'new' members identified by Shkolnik
    '2MASS J00164976+4515417',
    '2MASS J00193931+1951050',
    '2MASS J00194303+1951117',
    '2MASS J00281434-3227556',
    '2MASS J00413538-5621127',
    '2MASS J00482667-1847204',
    '2MASS J00501752+0837341',
    '2MASS J01303534+2008393',
    '2MASS J02241739+2031513',
    '2MASS J02335984-1811525',
    '2MASS J02450826-0708120',
    '2MASS J02485260-3404246',
    '2MASS J02495639-0557352',
    '2MASS J03255277-3601161',
    '2MASS J03363144-2619578',
    '2MASS J03370343-3042318',
    '2MASS J03393700+4531160',
    '2MASS J03550477-1032415',
    '2MASS J04232720+1115174',
    '2MASS J05015665+0108429',
    '2MASS J05061292+0439272',
    '2MASS J05363846+1117487',
    '2MASS J13215631-1052098',
    '2MASS J15063505-3639297',
    '2MASS J18011345+0948379',
    '2MASS J18055491-5704307',
    '2MASS J18090694-7613239',
    '2MASS J18092970-5430532',
    '2MASS J18435838-3559096',
    '2MASS J18471351-2808558',
    '2MASS J19082195-1603249',
    '2MASS J19260075-5331269',
    '2MASS J19300396-2939322',
    '2MASS J20083784-2545256',
    '2MASS J20085368-3519486',
    '2MASS J21200779-1645475',
    '2MASS J21384755+0504518',
    '2MASS J22085034+1144131',
    '2MASS J22334687-2950101',
    '2MASS J23010610+4002360',
    '2MASS J23355015-3401477',
])
