nohup python run_chronostar.py ../config/lcc.py &
nohup python run_chronostar.py ../config/ab_doradus.py & 
nohup python run_chronostar.py ../config/ic_2391.py & 
nohup python run_chronostar.py ../config/columba.py & 
nohup python run_chronostar.py ../config/octans.py & 
nohup python run_chronostar.py ../config/bpmg.py & 
nohup python run_chronostar.py ../config/tuc_hor.py & 
nohup python run_chronostar.py ../config/carina-near.py & 
nohup python run_chronostar.py ../config/carina.py & 
nohup python run_chronostar.py ../config/eta_cha.py & 
nohup python run_chronostar.py ../config/118_tau.py & 
nohup python run_chronostar.py ../config/32-ori.py & 
nohup python run_chronostar.py ../config/ucl.py & 
nohup python run_chronostar.py ../config/usco.py & 
nohup python run_chronostar.py ../config/upper-cra.py & 
nohup python run_chronostar.py ../config/twa_fit.py & 
