all: overlap

overlap: overlap.i
	swig -python overlap.i
	gcc -c overlap.c overlap_wrap.c -I /usr/include/python2.7 -lgsl -lgslcblas -lm
	ld -shared overlap.o overlap_wrap.o -o _overlap.so -lgsl -lgslcblas -lm


clean:
	rm -f overlap.o
	rm -f overlap_wrap.*
	rm -f _overlap.so
	rm -f overlap.pyc
	rm -f overlap.py
