all: overlap

_overlap.so: overlap.i
	swig -python overlap.i
	gcc -O3 -fPIC -c overlap.c overlap_wrap.c -I /pkg/linux/anaconda/include/python2.7 -lgsl -lgslcblas -lm
	ld -shared overlap.o overlap_wrap.o -o _overlap.so -lgsl -lgslcblas -lm

test: _test.so
	
overlap: _overlap.so
	
clean:
	rm -f overlap.o
	rm -f overlap_wrap.*
	rm -f _overlap.so
	rm -f overlap.pyc
	rm -f overlap.py
